# Generated by Django 3.0.8 on 2020-07-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rtsp_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, unique=True)),
                ('port', models.IntegerField(default=1026, null=True)),
                ('name', models.CharField(max_length=64)),
                ('longitude', models.CharField(max_length=64)),
                ('latitude', models.CharField(max_length=64)),
                ('address', models.CharField(default=0, max_length=256)),
                ('observation_area', models.CharField(default=0, max_length=256)),
                ('observation_target', models.CharField(default=0, max_length=256)),
                ('enable', models.PositiveSmallIntegerField(default=1)),
                ('bin_id', models.IntegerField(default=1026)),
                ('tide_level_name', models.CharField(max_length=64, null=True)),
                ('tide_level_code', models.CharField(max_length=64, null=True)),
                ('wave_heigh_name', models.CharField(max_length=64, null=True)),
                ('wave_heigh_code', models.CharField(max_length=64, null=True)),
                ('wave_direction_name', models.CharField(max_length=64, null=True)),
                ('wave_direction_code', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('enable', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
