"""
Django settings for hyjk project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xereke^%d804!9t0r_z@d+hqsh3bkltwfhe9@p#_&as(a*k@q3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'api',
    'django_crontab',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'hyjk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hyjk.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'hyjk',
        'USER': 'root',
        'PASSWORD': 'longbao',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

CACHES = {
          "default": {
                      "BACKEND": "django_redis.cache.RedisCache",
                      "LOCATION": "redis://:longbao@127.0.0.1:6379/1",
                      "OPTIONS": {
                                  "CLIENT_CLASS": "django_redis.client.DefaultClient",
                                 },
                     },
         }


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


LOGGING = {
           "version": 1,
           "disable_existing_loggers": False,

           "formatters": {
                          "standard": {
                                       "format": "[%(asctime)s] [%(levelname)s] %(message)s"
                                      },
                         },

           "handlers": {
                        "default": {
                                    "level": "DEBUG",
                                    "class": "logging.handlers.RotatingFileHandler",
                                    "filename": "/tmp/hyjk.log",
                                    "maxBytes": 1024 * 1024 * 50,
                                    "backupCount": 0,
                                    "formatter": "standard",
                                   },
                       },

           "loggers": {
                       "hyjk": {
                               "handlers": ["default"],
                               "level": "DEBUG",
                               "propagate": True,
                              },
                      },
          }

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_ALLOW_ALL = True
CORS_ORIGIN_WHITELIST = ()
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
TOKEN_TIME_OUT = 3600 * 24
VC_TOKEN_TIME = 3600 * 12

CRONTAB_COMMAND_PREFIX = 'LANG_ALL=zh_cn.UTF-8'

CRONJOBS = [

    ('*/5 * * * *', 'api.timer.timing','>> %s/log.log' % os.path.join(BASE_DIR, 'logs')),
]